// Generated by scripts/release-generate-processor-disclosures.py.
// Edit privacy/processors.json, not this file.
import Foundation

struct CloudProcessorDisclosure: Identifiable, Equatable, Sendable {
    let id: String
    let name: String
    let data: String
    let purpose: String
    let termsURL: URL
    let appearsInCloudProcessingDisclosure: Bool
}

enum CloudProcessorManifest {
    static let version = 5
    static let processors: [CloudProcessorDisclosure] = [
        CloudProcessorDisclosure(
            id: "deepgram",
            name: "Deepgram",
            data: "Real-time audio stream or bounded competitive-rep PCM with mip_opt_out=true",
            purpose: "Production speech-to-text transcription; competitive PCM is relayed through protected Firebase Functions when server observation is enabled",
            termsURL: URL(string: "https://deepgram.com/terms")!,
            appearsInCloudProcessingDisclosure: true
        ),
        CloudProcessorDisclosure(
            id: "apple-speech",
            name: "Apple Speech Recognition",
            data: "Short voice-question audio when the Apple fallback is used",
            purpose: "Ask Noum voice transcription; processing location depends on Apple's service and device availability",
            termsURL: URL(string: "https://www.apple.com/legal/privacy/")!,
            appearsInCloudProcessingDisclosure: true
        ),
        CloudProcessorDisclosure(
            id: "apple-location-mapkit",
            name: "Apple Core Location / MapKit",
            data: "Device coordinate when you request nearby-club search; a location passed to Apple geocoding for Path daylight only when permission already exists",
            purpose: "Nearby-club results and a cosmetic local day/night scene; iOS controls the location ultimately supplied",
            termsURL: URL(string: "https://www.apple.com/legal/privacy/")!,
            appearsInCloudProcessingDisclosure: false
        ),
        CloudProcessorDisclosure(
            id: "google-vertex-ai",
            name: "Google Vertex AI (Gemini)",
            data: "Speech transcript or Ask Noum message, bounded recent turns, bounded coaching context and session evidence, and selected video frames only when a production feature explicitly supports and requests visual feedback",
            purpose: "Production generated coaching and conversation responses",
            termsURL: URL(string: "https://cloud.google.com/terms")!,
            appearsInCloudProcessingDisclosure: true
        ),
        CloudProcessorDisclosure(
            id: "google-sign-in",
            name: "Google Sign-In",
            data: "The SDK vendor declaration covers linked account and device data when Google Sign-In is used",
            purpose: "Authentication and vendor-declared service diagnostics; Noum does not use it for advertising or cross-app tracking",
            termsURL: URL(string: "https://policies.google.com/privacy")!,
            appearsInCloudProcessingDisclosure: false
        ),
        CloudProcessorDisclosure(
            id: "firebase",
            name: "Firebase (Google)",
            data: "Bounded production coaching requests, Authentication and App Check proof, bounded competitive-rep PCM held in invocation memory with server-derived observation metadata, and short-lived mutual-connection invite secrets handled in invocation memory with digest-addressed account, display-name, pair, and timestamp records; account identity, optional sync data, Firebase installation data, and versioned Remote Config values are processed separately for account and configuration functionality",
            purpose: "Protected callable transport and abuse protection for cloud coaching, competitive observation, and mutual account connections, plus authentication, optional sync, first-run configuration, and vendor-declared diagnostics",
            termsURL: URL(string: "https://firebase.google.com/terms")!,
            appearsInCloudProcessingDisclosure: true
        ),
        CloudProcessorDisclosure(
            id: "open-meteo",
            name: "Open-Meteo",
            data: "A city or region label inferred from device time zone and locale, or supplied by app configuration; then coordinates returned by Open-Meteo itself",
            purpose: "Conversation weather context; Noum does not send a Core Location coordinate or account identifier",
            termsURL: URL(string: "https://open-meteo.com/en/terms")!,
            appearsInCloudProcessingDisclosure: false
        ),
    ]

    static let consentProcessors = processors.filter(\.appearsInCloudProcessingDisclosure)
}
