#!/usr/bin/env python3
"""Generate every shipping processor disclosure from one reviewed manifest."""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = ROOT / "privacy" / "processors.json"
MARKDOWN_PATH = ROOT / "Noum" / "PrivacyPolicy.md"
HTML_PATH = ROOT / "public" / "privacy.html"
SWIFT_PATH = ROOT / "Noum" / "CloudProcessorManifest.generated.swift"
START = "PROCESSOR-MANIFEST:START"
END = "PROCESSOR-MANIFEST:END"


def load_manifest() -> dict:
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    if set(manifest) != {
        "schemaVersion", "manifestVersion", "updatedAt", "processors"
    }:
        raise ValueError("Processor manifest has an unexpected top-level shape.")
    if manifest["schemaVersion"] != 1:
        raise ValueError("Unsupported processor manifest schema.")
    if not isinstance(manifest["manifestVersion"], int) or manifest["manifestVersion"] < 1:
        raise ValueError("Processor manifest version must be a positive integer.")
    expected = {
        "id", "name", "data", "purpose", "termsLabel", "termsURL",
        "requiresCloudProcessingConsent",
    }
    identifiers: set[str] = set()
    for processor in manifest["processors"]:
        if set(processor) != expected:
            raise ValueError("Processor entry has an unexpected shape.")
        identifier = processor["id"]
        if not isinstance(identifier, str) or not re.fullmatch(r"[a-z0-9-]+", identifier):
            raise ValueError("Processor ID is invalid.")
        if identifier in identifiers:
            raise ValueError(f"Duplicate processor ID: {identifier}")
        identifiers.add(identifier)
        for field in ("name", "data", "purpose", "termsLabel"):
            value = processor[field]
            if not isinstance(value, str) or not value.strip() or value != value.strip():
                raise ValueError(f"Invalid {field} for {identifier}.")
        terms = urlparse(processor["termsURL"])
        if terms.scheme != "https" or not terms.netloc:
            raise ValueError(f"Processor terms URL must be HTTPS: {identifier}")
        if not isinstance(processor["requiresCloudProcessingConsent"], bool):
            raise ValueError(f"Invalid consent flag for {identifier}.")
    return manifest


def markdown_block(processors: list[dict]) -> str:
    rows = [
        f"<!-- {START} -->",
        "| Service | Data Shared | Purpose | Data Terms |",
        "|---------|-------------|---------|------------|",
    ]
    for item in processors:
        name = item["name"].replace("|", "\\|")
        data = item["data"].replace("|", "\\|")
        purpose = item["purpose"].replace("|", "\\|")
        label = item["termsLabel"].replace("|", "\\|")
        rows.append(
            f"| **{name}** | {data} | {purpose} | "
            f"[{label}]({item['termsURL']}) |"
        )
    rows.append(f"<!-- {END} -->")
    return "\n".join(rows)


def html_block(processors: list[dict]) -> str:
    rows = [
        f"    <!-- {START} -->",
        "    <table>",
        "      <thead><tr><th>Service</th><th>Data Shared</th><th>Purpose</th></tr></thead>",
        "      <tbody>",
    ]
    for item in processors:
        rows.append(
            "        <tr>"
            f"<td><strong>{html.escape(item['name'])}</strong></td>"
            f"<td>{html.escape(item['data'])}</td>"
            f"<td>{html.escape(item['purpose'])}. "
            f"<a href=\"{html.escape(item['termsURL'], quote=True)}\">"
            f"{html.escape(item['termsLabel'])}</a>.</td>"
            "</tr>"
        )
    rows.extend(["      </tbody>", "    </table>", f"    <!-- {END} -->"])
    return "\n".join(rows)


def swift_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def swift_source(manifest: dict) -> str:
    rows = [
        "// Generated by scripts/release-generate-processor-disclosures.py.",
        "// Edit privacy/processors.json, not this file.",
        "import Foundation",
        "",
        "struct CloudProcessorDisclosure: Identifiable, Equatable, Sendable {",
        "    let id: String",
        "    let name: String",
        "    let data: String",
        "    let purpose: String",
        "    let termsURL: URL",
        "    let requiresCloudProcessingConsent: Bool",
        "}",
        "",
        "enum CloudProcessorManifest {",
        f"    static let version = {manifest['manifestVersion']}",
        "    static let processors: [CloudProcessorDisclosure] = [",
    ]
    for item in manifest["processors"]:
        rows.extend([
            "        CloudProcessorDisclosure(",
            f"            id: {swift_string(item['id'])},",
            f"            name: {swift_string(item['name'])},",
            f"            data: {swift_string(item['data'])},",
            f"            purpose: {swift_string(item['purpose'])},",
            f"            termsURL: URL(string: {swift_string(item['termsURL'])})!,",
            "            requiresCloudProcessingConsent: "
            f"{'true' if item['requiresCloudProcessingConsent'] else 'false'}",
            "        ),",
        ])
    rows.extend([
        "    ]",
        "",
        "    static let consentProcessors = processors.filter(\\.requiresCloudProcessingConsent)",
        "}",
        "",
    ])
    return "\n".join(rows)


def replace_block(source: str, block: str) -> str:
    pattern = re.compile(
        rf"^[^\n]*<!-- {re.escape(START)} -->.*?"
        rf"<!-- {re.escape(END)} -->[^\n]*$",
        flags=re.MULTILINE | re.DOTALL,
    )
    if len(pattern.findall(source)) != 1:
        raise ValueError("Expected exactly one generated processor block.")
    return pattern.sub(block, source)


def expected_outputs(manifest: dict) -> dict[Path, str]:
    processors = manifest["processors"]
    return {
        MARKDOWN_PATH: replace_block(
            MARKDOWN_PATH.read_text(encoding="utf-8"),
            markdown_block(processors),
        ),
        HTML_PATH: replace_block(
            HTML_PATH.read_text(encoding="utf-8"),
            html_block(processors),
        ),
        SWIFT_PATH: swift_source(manifest),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    try:
        manifest = load_manifest()
        outputs = expected_outputs(manifest)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"Processor disclosure generation failed: {error}", file=sys.stderr)
        return 1
    if arguments.check:
        stale = [path for path, expected in outputs.items()
                 if not path.exists() or path.read_text(encoding="utf-8") != expected]
        if stale:
            print("Generated processor disclosures are stale:", file=sys.stderr)
            for path in stale:
                print(f"- {path.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print("Processor manifest and generated disclosures match.")
        return 0
    for path, expected in outputs.items():
        path.write_text(expected, encoding="utf-8")
    print("Generated processor disclosures updated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
